### ISSUE TITLE
Images not viewable for chmod permissions

### ISSUE THREAD

**Issue by Askancy** [rolandstarke/laravel-thumbnail#10]
Since I upgraded to Laravel 9 and PHP 8.1.5, I've noticed that it correctly creates thumbnails but they are not showing.

In checking the routes I noticed that:

/httpdocs/storage/crops/news/1z/yz
yz = 0700

towrmhfoogoog48ow4osc.jpg
0644
if I put permissions 0755 on folders and files the images will be viewable...

**Comment by rolandstarke** [comment]
Thanks for the report.


It looks like you are not the only one: https://laracasts.com/discuss/channels/laravel/laravel-9-storage-permission

For a solution idk yet.

**Comment by rolandstarke** [comment]
Would it be ok for you to set the visibility to `'public'` for the whole filesystem?

https://github.com/laravel/laravel/blob/d0603437cbbb478586979a3792d49e0d157ce554/config/filesystems.php#L43

**Comment by Askancy** [comment]
I have solved with the permissions to the filesystem, I had missed this configuration

Strange because with Laravel 7 I didn't put the permissions... 😅

Thank you so much for the great package and support you give @rolandstarke .
