### ISSUE TITLE
Folder no exist

### ISSUE THREAD

**Issue by lerevolte** [rolandstarke/laravel-thumbnail#12]
{{ Thumbnail::src(public_path($photo->path))->smartcrop(200, 200)->url() }} - return path. But folder "thumbnails" not created

**Comment by rolandstarke** [comment]
Generating the url does not create the thumbnails folder.


Opening the url should create the thumbnail. Do you get an error when opening the url?

**Comment by VivekanandhanT** [comment]
@rolandstarke Yes, when trying to open the URL returns a 404 Not Found Error.

**Comment by rolandstarke** [comment]
With the default config you should get an URL like:


```php
echo \Thumbnail::src('https://picsum.photos/200')->url();
// http://localhost:8000/storage/thumbnails/default/ac/o1/s7nfb1ssk0wkow44k8ogc.jpg?p=picsum.photos%2F200&s=https
```

The URL should be visible in your laravel routes:
```sh
php artisan route:list
  ...
  GET|HEAD   storage/thumbnails/avatar/{file} ................................................ Rolandstarke\Thumbnail › ImageController@index  
  GET|HEAD   storage/thumbnails/default/{file} ............................................... Rolandstarke\Thumbnail › ImageController@index

```

Is that the case for you too? 
Else how do you run the laravel app? 
I use `php artisan serve`.
