### ISSUE TITLE
Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by Askancy** [rolandstarke/laravel-thumbnail#14]
OS: Mac OSX
PHP: 8.1.6
Laravel: 9.11

`Deprecated: sha1(): Passing null to parameter #1 ($string) of type string is deprecated in /Applications/XAMPP/xamppfiles/htdocs/Project/config/thumbnail.php on line 9`

**Comment by rolandstarke** [comment]
Thank you.


That should ne fixed with

php artisan key:generate
