### ISSUE TITLE
Scoped filesystem driver not compatible

### ISSUE THREAD

**Issue by Askancy** [rolandstarke/laravel-thumbnail#16]
Scopes are not compatible, you get an error that it does not have permission to access the file.

https://github.com/laravel/framework/pull/44105

**Comment by rolandstarke** [comment]
Hey, thanks for the report.

The error you are getting is like: `Source is not allowed. Given path "1.jpg" on disk "test"`?

I got the above error when trying it myself with:
`\Thumbnail::src('1.jpg', 'test')>url();`
It looks like the library needs the leading slash. With the following code it worked:
`\Thumbnail::src('/1.jpg', 'test')>url();`

I will update the library to support omitting the leading slash.

**Comment by Askancy** [comment]
Thank you for your reply @rolandstarke 

I currently have this and it works:
`{{ Thumbnail::preset('gallery')->src('bucket/gallery/'.$value->path, 's3')->url(true) }}`

to sort it all out I'm implementing filesystems with scope, and here's the scope I'm using:

```
        's3_gallery' => [
            'driver' => 'scoped', // This is the new scoped driver!
            'disk' => 's3',       // It uses the `s3` disk above
            'prefix' => 'bucket/gallery',
        ],
```
So here is the new code, I get the error, however::
`{{ Thumbnail::preset('gallery')->src($value->path, 's3_gallery')->url(true) }}`
>Source is not allowed. Given path "2472/mO84aKBl6lpQnxPNDyPt5gltlge.webp" on disk "s3_gallery"

I tried as you say, with the slash in front, but I keep getting the error:

`{{ \Thumbnail::preset('gallery')->src($value->path, 's3_gallery')->url(true) }}`

I believe that he has problems using the scoped filesystem

**Comment by rolandstarke** [comment]
I believe the issue could be that in `/config/thumbnail.php` you would need to add the new disk as an allowed source. I hope then it works.

```
    'allowedSources' => [
        'a' => app_path(),
        'r' => resource_path(),
        'p' => public_path(),
        's' => storage_path(),
        'http' => 'http://', //allow images to be loaded from http
        'https' => 'https://',
        'ld' => ['disk' => 'local', 'path' => '/'], //allow images to be loaded from `Storage::disk('local')`
        'pd' => ['disk' => 'public', 'path' => '/'],
        's3_g' => ['disk' => 's3_gallery', 'path' => '/'], // <-- add the new disk
    ],
```

**Comment by rolandstarke** [comment]
I saw that in laravel the filesystem path param does not need a leading slash. I released v1.0.8. Now you can configure the path without the slash like this:


 ```
   'allowedSources' => [
        'a' => app_path(),
        'r' => resource_path(),
        'p' => public_path(),
        's' => storage_path(),
        'http' => 'http://', //allow images to be loaded from http
        'https' => 'https://',
        'ld' => ['disk' => 'local', 'path' => ''], //allow images to be loaded from `Storage::disk('local')`
        'pd' => ['disk' => 'public', 'path' => ''],
        's3_g' => ['disk' => 's3_gallery', 'path' => ''], // <-- add the new disk
    ],
```

**Comment by Askancy** [comment]
Thank you very much, the files are now read correctly.  Just a small note though:
I added in thumbnail.php:

in allowedSources
`'s3_g' => ['disk' => 's3_gallery', 'path' => ''],`

`s3_g` What would it stand for? this parameter when used? in my blade i used:

`{{ Thumbnail::preset('gallery')->src($value->path, 's3_gallery')->url() }}`

It would be really nice if it read data from filesystems.php instead of having to indicate routes. anyway great job, definitely the best thumbnail package

**Comment by rolandstarke** [comment]
`s3_g` can be any string you want. You don't need and can't use it anywhere. It's used by the library as a param in the URL. `?s=s3_g`. I picked a short name, so that the URL does not get longer than needed.


Thanks for the feedback. Allowing every disk from the filesystems.php would simplify the usage of the library.  So that you don't need to fiddle around with the allowedSources settings. I am not sure if users rely on the security to list every disk they want to load images from.
