### ISSUE TITLE
Delete single thumbnail

### ISSUE THREAD

**Issue by wcaaan** [rolandstarke/laravel-thumbnail#2]
How should i delete single thumbnail ? if the src picture updates the old thumbnail is cached.

**Comment by rolandstarke** [comment]
Hey, you can now delete images with:
```php
//save image
\Thumbnail::src('/cat.jpg', 'public')->smartcrop(64, 64)->save();

//delete image
\Thumbnail::src('/cat.jpg', 'public')->smartcrop(64, 64)->delete();
```


If the image is cached in the browser you would need to generate a new URL to bypass the cache. For example changing the source image path will generate a new URL. (changed `'/cat.jpg'` to `'/cat_v2.jpg'`)

```php
\Thumbnail::src('/cat_v2.jpg', 'public')->smartcrop(64, 64)->url();
```
