### ISSUE TITLE
CDN Storage Thumbnail Creation Error

### ISSUE THREAD

**Issue by Askancy** [rolandstarke/laravel-thumbnail#3]
I found this packages by accident, and I already like it so much but I have a question. I have the original images in a DigitalOcean Spaces CDN called in Laravel's filesystem “do_spaces”.

So the image for example is:

`\Thumbnail::src('projectx/article/00b9c8c0e4123c441353050cceafb173.jpg', 'do_spaces' );`

How can I make him save me image in:

`projectx/crops/.*`

in config:

```
        'ld' => ['disk' => 'do_spaces', 'path' => 'projectx/'], //allow images to be loaded from `Storage::disk('local')`
        'pd' => ['disk' => 'do_spaces', 'path' => 'projectx/'],
```
```
            'destination' => ['disk' => 'do_spaces', 'path' => 'projectx/crops/'],
```

Blade:
`{{ Thumbnail::src('projectx/article/00b9c8c0e4123c441353050cceafb173.jpg', 'do_spaces')->url() }}
`

but when the url is generated in the blade:

`https://***.ams3.digitaloceanspaces.com/projectx/crops/db9/ag5cy0kooo40w4g4go0so8.jpg%3Fp%3Darticle%252F00b9c8c0e4123c441353050cceafb173.jpg%26s%3Dld
`

and the image does not exist, where am I wrong?

**Comment by rolandstarke** [comment]
Hey, thanks.

The config looks good.
The problem is when calling `->url()` it is actually not checked if the crop is there.

You could use `->url(true);` to ensure its presence. [docs](https://rolandstarke.github.io/laravel-thumbnail/url.html)

A problem of this would be that it slows down the `->url` call. The intended workflow would be that every 404 from the digital ocean space would forward the request to your laravel application.

**Comment by Askancy** [comment]
Thank you so much, the image is properly stored, even if it generates db9 folders etc... Obligatory this thing?

Unfortunately the images generates them with private permits.

I take the opportunity of your availability to ask you another question,  digitalocean's cdn has a url like: 
`https://***.ams3.digitaloceanspaces.com/projectx/`
can i print the correct url with the package:cdn.domain.tdl?

**Comment by rolandstarke** [comment]
The 3 char subdirs (db9) are oblicatory so far. The intention behind it is to prevent too many files in the same directory.

Great you could fix the visibility!

With the costume subdomain for the do space i don't really know too. This lib just calls `echo Storage::disk('do_spaces')->url('image.jpeg')`. So the url generation is outside of this library.

**Comment by Askancy** [comment]
ok i'm doing a url cleanup and a conversion, casomai i'll generate the url with a function, 

i still don't understand why it prints:
`<img src="https://projectx.ams3.digitaloceanspaces.com/gamelite/crops/23c/xr26nkme8cs088sg4g88kk.webp%3Fcrop%3D150x150%26format%3Dwebp%26p%3Darticolo%252F06e0676974c5981a729328a99d598cb7.jpg%26s%3Dld">`

instead of

`<img src="https://projectx.ams3.digitaloceanspaces.com/gamelite/crops/23c/xr26nkme8cs088sg4g88kk.webp">`

repeats me the path and name of the original file... `%3Fcrop%3D150x150%26format%3Dwebp%26p%3Darticolo%252F06e0676974c5981a729328a99d598cb7.jpg%26s%3Dld`

Thank you so much, the packages works really well, I really hope it helps me solve the problem of the final printed url so I can start implementing it completely in the project.

**Comment by rolandstarke** [comment]
Ty, sorry. Mm you are right, if the crop is already there the params in the url are no longer needed so you could remove everything after the `?` like:

`{{ strstr(Thumbnail::src('projectx/article/00b9c8c0e4123c441353050cceafb173.jpg', 'do_spaces')->url(), '?', false) }}`

**Comment by Askancy** [comment]
Ok thank you so much Roland! fixed with:

`<img src="{{ re_cdn(Thumbnail::src('projectx/article/003515a5bbf55b9b434e00afb3313d74.jpg', 'do_spaces')->url(true)) }}">
`

```
function re_cdn($e) {
	return str_replace("projectx.ams3.digitaloceanspaces.com", "cdn.projectx.net", strstr($e, '%', true));
}
```

fantastic packages

**Comment by Askancy** [comment]
Everything works perfectly, but I'm having a load issue, let me know of course if I have to open a new ticket for this.

Since I inserted the thumbnail cutout on the fly, my TTFB has increased a lot, reaching 3.6 seconds.

basically, this is one of many crop facts:

` <img data-src="{{ re_cdn(Thumbnail::preset('news')->src(''.$value->immagine(), 's3')->url(true)) }}" class="lazyload">`


the "true" I need to make thumbnails generate when it doesn't exist, i don't understand why it's so slow at loading...

**Comment by rolandstarke** [comment]
Hey,

I can confirm that its slow with `->url(true)`. In combination with an external storage. The slow part here is checking if the thumbnail already exists.


I tested on digital ocean with the do spaces:

```
   //first test: filesystem is not touched, just the url is generated
    $start = microtime(true);
    for ($i = 0; $i < 30; $i++) {
        Thumbnail::src('https://picsum.photos/200')->url();
    }
    var_dump(microtime(true) - $start);  //<1ms

    //second test: it is checked on the local filesystem if the thumbnail is there
    $start = microtime(true);
    for ($i = 0; $i < 30; $i++) {
        Thumbnail::src('https://picsum.photos/200')->url(true);
    }
    var_dump(microtime(true) - $start); //1ms

    //third test: it is checked on the do spaces if the thumbnail is there
    $start = microtime(true);
    for ($i = 0; $i < 30; $i++) {
        Thumbnail::preset('news')->src('https://picsum.photos/200')->url(true);
    }
    var_dump(microtime(true) - $start); //300ms
```

**Comment by Askancy** [comment]
so your best choice is to keep the original image on S3 and the thumbnail on server right?

is the configuration correct like that? because it doesn't create my folder...

```
        'default' => [
            'destination' => ['disk' => 'local', 'path' => 'public/upload/crops/', 'format' => 'webp'],
        ],
```

blade:

`<img data-src="{{ Thumbnail::preset('news')->src('project/'.$value->immagine(), 's3')->url(true) }}" alt="{!! $value->titolo !!}" class="d-flex align-self-center mr-3 thumb-news lazyload">
`
thank you so much roland

**Comment by rolandstarke** [comment]
`'destination' => ['disk' => 'public', 'path' => '/upload/crops/'],`

```
php artisan storage:link
```
